export const allProductsData = [
  {
    id: "1",
    name: "Rohu Fish",
    description: "Fresh Rohu fish, cleaned and gutted",
    category: "Fish",
    price: 5.99,
    discount: 0,
    available: "Available",
    imageUrl: "https://example.com/images/rupchand_fish.jpg",
    brand: "Fresh Water",
    weight: 500,
    unit: "g",
    rating: 4.5,
    numReviews: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
    expiryDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    storageTemperature: "0-4",
    isHalal: true,
    origin: "Andhra Pradesh",
  },
  {
    id: "2",
    name: "Katla Fish",
    description: "High quality Katla fish, cleaned and gutted",
    category: "Fish",
    price: 6.99,
    discount: 0,
    available: "Available",
    imageUrl: "https://example.com/images/rupchand_fish.jpg",
    brand: "Fresh Water",
    weight: 500,
    unit: "g",
    rating: 4.7,
    numReviews: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
    expiryDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    storageTemperature: "0-4",
    isHalal: true,
    origin: "Andhra Pradesh",
  },
  {
    id: "3",
    name: "Rupchand Fish",
    description: "Fresh Rupchand fish, cleaned and gutted",
    category: "Fish",
    price: 7.99,
    discount: 10,
    available: "Available",
    imageUrl: "https://example.com/images/rupchand_fish.jpg",
    brand: "Fresh Water",
    weight: 500,
    unit: "g",
    rating: 4.2,
    numReviews: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
    expiryDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    storageTemperature: "0-4",
    isHalal: true,
    origin: "Andhra Pradesh",
  },
  {
    id: "4",
    name: "Pangas Fish",
    description: "Farm fresh Pangas fish, cleaned and gutted",
    category: "Fish",
    price: 4.99,
    discount: 5,
    available: "Available",
    imageUrl: "https://example.com/images/pangas_fish.jpg",
    brand: "Fresh Water",
    weight: 500,
    unit: "g",
    rating: 4.3,
    numReviews: 110,
    createdAt: new Date(),
    updatedAt: new Date(),
    expiryDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    storageTemperature: "0-4",
    isHalal: true,
    origin: "Andhra Pradesh",
  },
  {
    id: "5",
    name: "Local Rohu Fish",
    description: "Locally sourced fresh Rohu fish",
    category: "Fish",
    price: 5.49,
    discount: 0,
    available: "Not Available",
    imageUrl: "https://example.com/images/local_rohu_fish.jpg",
    brand: "Local Catch",
    weight: 500,
    unit: "g",
    rating: 4.6,
    numReviews: 80,
    createdAt: new Date(),
    updatedAt: new Date(),
    expiryDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    storageTemperature: "0-4",
    isHalal: true,
    origin: "Local",
  },
  {
    id: "6",
    name: "Local Katla Fish",
    description: "Locally sourced high quality Katla fish",
    category: "Fish",
    price: 6.49,
    discount: 0,
    available: "Available",
    imageUrl: "https://example.com/images/local_katla_fish.jpg",
    brand: "Local Catch",
    weight: 500,
    unit: "g",
    rating: 4.8,
    numReviews: 90,
    createdAt: new Date(),
    updatedAt: new Date(),
    expiryDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    storageTemperature: "0-4",
    isHalal: true,
    origin: "Local",
  },
  {
    id: "7",
    name: "Local Pangas Fish",
    description: "Locally farmed fresh Pangas fish",
    category: "Fish",
    price: 4.49,
    discount: 0,
    available: "Not Available",
    imageUrl: "https://example.com/images/local_pangas_fish.jpg",
    brand: "Local Catch",
    weight: 500,
    unit: "g",
    rating: 4.4,
    numReviews: 70,
    createdAt: new Date(),
    updatedAt: new Date(),
    expiryDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    storageTemperature: "0-4",
    isHalal: true,
    origin: "Local",
  },
  {
    id: "8",
    name: "Prawns",
    description: "Fresh prawns, cleaned and deveined",
    category: "Prawns",
    price: 9.99,
    discount: 0,
    available: "Available",
    imageUrl: "https://example.com/images/prawns.jpg",
    brand: "Fresh Water",
    weight: 500,
    unit: "g",
    rating: 4.9,
    numReviews: 150,
    createdAt: new Date(),
    updatedAt: new Date(),
    expiryDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    storageTemperature: "-1 to 1",
    isHalal: true,
    origin: "West Bengal",
  },
  {
    id: "9",
    name: "Local Prawns",
    description: "Locally sourced fresh prawns",
    category: "Prawns",
    price: 8.99,
    discount: 0,
    available: "Not Available",
    imageUrl: "https://example.com/images/local_prawns.jpg",
    brand: "Local Catch",
    weight: 500,
    unit: "g",
    rating: 4.7,
    numReviews: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
    expiryDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    storageTemperature: "-1 to 1",
    isHalal: true,
    origin: "Bihar",
  },
];
